### ISSUE TITLE
Experience section >> 

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#14]
At times, When we return to Experience section, we see a blank window.

Please refer the screenshot.

Device : Desktop
Browser : All
OS : All

![ie11_experience](https://user-images.githubusercontent.com/17753858/38089701-f963b3fe-337d-11e8-9cb9-b5c9c8330018.png)

**Comment by omniwired** [comment]
is random?
Happens more often if you are logged in?

**Comment by SycamoreFoxQA** [comment]
Yes, the issue occurs randomly.

We could not find a scenario for this.

And today this issue is not observed.

Hence closing this issue.
