### ISSUE TITLE
Explore section >> Video Playing issue >> 

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#2]
There are two videos in >> Explore >> Na’vi Ritual at the Tree of Souls >>Together Before Eywa >> 

When we play both the videos simultaneously, both the videos start.

Ideally, one video should be paused if the another one is playing.

Device : All
Browser : All 
OS : All

**Comment by SycamoreFoxQA** [comment]
Issue still persists.

**Comment by omniwired** [comment]
@damyantid out of scope

**Comment by damyantid** [comment]
Agreed.

**Comment by SycamoreFoxQA** [comment]
OK.
