### ISSUE TITLE
Query >> Home section >> Take You Quiz >> 

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#23]
We could not understand on what basis the result is shown after completing the quiz.

Please refer the screenshot.

Device : Desktop
Browser : All
OS : All

![quiz_result](https://user-images.githubusercontent.com/17753858/38090028-f6cdb60c-337e-11e8-908e-75ad9e58811f.png)

**Comment by omniwired** [comment]
I don't understand it either. But is like this

**Comment by SycamoreFoxQA** [comment]
OK .Closing the issue as per the comment.
