### ISSUE TITLE
Query >> Home section >> Photo Of the Week >> 

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#24]
There is only one photo  in Photo Of the Week section.

Same is observed for Featured Video.

Is it fine?

Device : Desktop
Browser : All
OS : All

**Comment by omniwired** [comment]
@damyantid is like this on the current site.

**Comment by damyantid** [comment]
Damyanti Dayaram
Project Manager, FDIT

Sent via the Samsung Galaxy Note8, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by omniwired** [comment]
I think your last message didn't get through.

**Comment by damyantid** [comment]
Yes, this is fine.

**Comment by SycamoreFoxQA** [comment]
OK.
