### ISSUE TITLE
Query >> Redirection of 'GO TO ACE' link >> 

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#26]
'GO TO ACE' redirects us to >> 

https://disneyworld.disney.go.com/destinations/animal-kingdom/pandora-world-of-avatar/

Is it fine?

Device : Desktop
Browser : All
OS : All

**Comment by SycamoreFoxQA** [comment]
@damyantid Is it fine to close?

**Comment by damyantid** [comment]
Yes, please close.

**Comment by SycamoreFoxQA** [comment]
Closing the issue as per comment.
