### ISSUE TITLE
Query >> Redirection of 'GO TO DISCOVER PANDORA' link >> 

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#27]
'GO TO DISCOVER PANDORA' redirects us to >>

http://www.avatardiscoverpandora.com/

Is it fine?

Device : Desktop
Browser : All
OS : All

**Comment by SycamoreFoxQA** [comment]
@damyantid Is it fine to close?

**Comment by damyantid** [comment]
Yes, this is fine. Will close the ticket.

**Comment by SycamoreFoxQA** [comment]
OK.
