### ISSUE TITLE
Query >> About >> Partners >> ACE

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#28]
In the About Tab >> Partners Section >>

The second partner logo is seen as "ACE" but it redirects to "https://disneyworld.disney.go.com/destinations/animal-kingdom/pandora-world-of-avatar/"

Is that fine? 

Device : Desktop
Browser : All 
OS : All

**Comment by omniwired** [comment]
yes, it's fine

**Comment by SycamoreFoxQA** [comment]
OK. Closing the issue as per the comment.
