### ISSUE TITLE
Query >> About >> Partners 

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#29]
In the About Tab >> Partners Section >>

There are 5 partners logo, among which only three are functional viz., 
• ACE
• 20th Century Fox
• GES

Following partner logos are not functional:

• RDA
• LightStorm

Is it intentional?

Please refer screenshot.

Device : Desktop
Browser : All 
OS : All

![partners about](https://user-images.githubusercontent.com/17753858/38090214-849ee708-337f-11e8-9148-970b207622f8.png)

**Comment by omniwired** [comment]
yeah, I noticed this one too; but seems to be OK, as it's the same behaviour in avatar.com.

**Comment by SycamoreFoxQA** [comment]
OK. Closing as per comment.
