### ISSUE TITLE
Query >> Android tablets >> Device Orientation issue >> Missing text

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#33]
In android tablets, for the portrait mode, we can see the text "Get the very latest from Pandora. Join PRF" below the About section.

However, in landscape mode, the same text seems to be missing.

Also the follow us icons seems to be missing in the landscape mode

Please refer screenshot. 

Devices: Tablets
Browser: Chrome 64.0 
OS: Android 7.1.1

![and_white-tab_portrait](https://user-images.githubusercontent.com/17753858/38090628-cbdcb018-3380-11e8-9f4a-4a64611d2ea0.jpg)

**Comment by SycamoreFoxQA** [comment]
Issue still persists.

**Comment by omniwired** [comment]
fixed in the other ticket

**Comment by SycamoreFoxQA** [comment]
OK.
