### ISSUE TITLE
Query >> All Mobiles / Tablets >> Tab Highlighting issue

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#35]
In all tablets, the footer tabs seems to be highlighted even when we close the tab.
However, if we tap else where the highlighting effect disappears.

Is that fine?

Please refer screenshot. 

Devices: Mobiles, Tablets
Browser: Chrome 64, Safari 11.0, 10.0
OS: Android 7.1.1, iOS 11.2.1

![air_footer_highlighting](https://user-images.githubusercontent.com/17753858/38090688-00236ee8-3381-11e8-9909-af06b7da9ba1.PNG)

**Comment by SycamoreFoxQA** [comment]
Issue still persists.

**Comment by omniwired** [comment]
I wasn't able to reproduce.
Google Pixel 2 XL (Chrome 65) and a Nexus 7 tablet.
Is safe to ignore this one, too small.

**Comment by SycamoreFoxQA** [comment]
@omniwired 
Ok. Closing the issue as per the comment.
