### ISSUE TITLE
Sign Up >> Close button issue

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#44]
When we load the site for the first time and click on "Sign up" we get an age gate window.

However, there is no close button present.

Also we need to enter the date of birth to close it or to open any other tab.

Devices: All
Browser: All
OS: All

**Comment by omniwired** [comment]
the legal department went through it and it's the same behaviour on the live site.

**Comment by SycamoreFoxQA** [comment]
OK. Closing the issue as per the comment.
