### ISSUE TITLE
SUBMIT FEEDBACK >> Not functional if logged in

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#51]
If we are logged in and then click on the SUBMIT FEEDBACK button, only a blank overlay appears.

Devices: All
OS: All
Browsers: All

**Comment by omniwired** [comment]
confirmed

**Comment by omniwired** [comment]
great finding!

**Comment by SycamoreFoxQA** [comment]
Closing the issue as it is fixed
