### ISSUE TITLE
IE 11 >> Contents loading issue

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#56]
While browsing through the site, the site contents are not seen.
Only blank screen is seen.

Also, the site performance is low on IE 11 as compared to other browsers.

Devices: Desktop
OS: Windows 10
Browsers: IE 11

**Comment by omniwired** [comment]
This is a Javascript heavy site, so the slowness of the old browser engine can't be helped.

**Comment by SycamoreFoxQA** [comment]
Ok. Closing as per comment.
