### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#9]
When we sign up, we are able to create our profile. But when we save our details, the site says "Your details are saved" but the page does not reload and it stays on the same page and Save button is seen and it is clickable. 

Ideally when we save any changes, we should be redirected to home page or the previous page.

Please refer screenshot.
Device : Desktop
Browser : All 
OS : All

![save_profile](https://user-images.githubusercontent.com/17753858/38089671-ef78ff16-337d-11e8-89f6-9606114b44c1.png)

**Comment by SycamoreFoxQA** [comment]
Issue still persists.

**Comment by omniwired** [comment]
Seems it has been approved to be like this, I checked the live site www.avatar.com it has the same behaviour.

**Comment by SycamoreFoxQA** [comment]
@omniwired 
Ok. closing the issue as per the comment.
